# Site settings
TZ: Europe/Kiev
title: Vazha Omanashvili - Full Stack Developer
domain: vazha.me
url: http://vazha.me
repo: https://github.com/rainum/vazha.me

# Global data
author: Vazha Omanashvili
email: rainum.ua@gmail.com
description: >
  Vazha Omanashvili is a Ukraine based Full Stack Developer who likes to develop an awesome stuff.

about_me: |
  ### Hello!

  My name is Vazha Omanashvili. I'm a Full Stack Developer from Ukraine.

  Currently I'm working at [Stoplight](https://stoplight.io/). We're providing engineering
  teams with the best way to document, test, and build web APIs. I meddle with
  everything related to: APIs, NodeJS, GraphQL, Meteor, MongoDB, React, Electron. Sometimes 
  I'm contributing into an open-source projects.

  I love to build things which are useful for people, especially developer tools. I'm 
  fascinated by any engineering, rock music, bleeding edge of technology, and interesting books.

  [Download my CV](https://drive.google.com/uc?export=download&id=0B-YBgjOTa-EnZ1BxNWppZ0luOWM)

google_analytics_id: UA-7589447-3
twitter_username: vazhaom
github_username: rainum
linkedin_profile: https://www.linkedin.com/in/vazha
meta:
  - name: author
    content: Vazha Omanashvili

  - name: copyright
    content: Vazha Omanashvili

# Collections
collections:
 - projects

# Build settings
minify_html: true
markdown: kramdown
exclude:
 - README.md
 - .gitignore
 - autoprefixer.yml
 - Gemfile
 - Gemfile.lock

assets:
  compress:
    css: true
    js: true
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

gems:
  - jekyll-assets
  - octopress-minify-html
